### ISSUE TITLE
Create sub-repository and separate Django APP for Workflows (Templates) 

### ISSUE THREAD

**Issue by glind** [buildlyio/buildly-core#212]
# Feature Request
Each component should be added as an optional at build or post build component that can be toggled on or off.  

## Proposal
For Workflow we will need to move it out of the primary buildly-core repository into it's own repo that can be added as a sub-repository when enabled in the admin UI or CLI.
# Bug report
N/A

## Current behavior
Workflow is included with each clone of the repository as part of the main repo not a sub repository and can not be toggled off.  All dependencies are required across models and views.

## Expected behavior
User should be able to remove or comment out the inclusion of the app from the settings file and the app should still function but without workflow functionality. 

## Enviroment
Buildly version : x.y.z
Logs: ``

**Comment by glind** [comment]
Really this is about the configuration file and what sub apps are configured for an instance of Buildly.  See CLI tools

**Comment by jefmoura** [comment]
I won't be done
