### ISSUE TITLE
Api for login  '/oauth/token'  returning status '500' with no proper error message for incorrect username/password

### ISSUE THREAD

**Issue by ghost** [buildlyio/buildly-core#318]
If user enters any of the fields(username/password) incorrect the api should return a proper "invalid credentials" error message with a proper status code...

## Current behavior
api returns status **500 Internal Server Error** with no proper error message.

## Expected behavior
Should returns error message for incorrect credentials..

**Comment by jefmoura** [comment]
Thank you for pointing this issue out @komal-joshi-kiwitech 
This is an issue with one of the Buildly Core dependencies called `django-oauth-toolkit` and a fix was already released for it (https://github.com/jazzband/django-oauth-toolkit/pull/812).
With the PR https://github.com/buildlyio/buildly-core/pull/325, we're upgrading the version of the library to the newest one that includes the needed fix.
