### ISSUE TITLE
Password should not be a required field in edit core user request object.

### ISSUE THREAD

**Issue by ghost** [buildlyio/buildly-core#323]
# Feature Request
In api to edit a coreuser (**/coreuser/{id}**) we have to pass the password field in the request object which in-fact is a required field.

## Proposal
Password field should not be present(in this case required) in the request object of edit as it is not good for security point of view.

**Comment by jefmoura** [comment]
@komal-joshi-kiwitech thank you for creating the issue but the API is working as expected. If we send a PUT request to update an object, we have to provide all the required fields. In the other hand, if we want to update an object partially, we should send a PATCH request with the partial query parameter as shown below:
```bash
curl --location --request PATCH 'http://localhost:8080/coreuser/1/?partial=true' \
--header 'Content-Type: application/json' \
--header 'Authorization: JWT <token>' \
--data-raw '{
  "first_name": "New First Name",
  "last_name": "New Last Name",
  "email": "new@example.com",
  "title": "mr"
}'
```

```
PATCH /coreuser/1/?partial=true HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: JWT <token>

{
  "first_name": "New First Name",
  "last_name": "New Last Name",
  "email": "new@example.com",
  "title": "mr"
}
```
